import { commonMy, commonEn } from "./common";
import { my as posMy, en as posEn } from "./pos";
import { my as ordersMy, en as ordersEn } from "./orders";
import { my as kdsMy, en as kdsEn } from "./kds";
import { my as tablesMy, en as tablesEn } from "./tables";
import { my as menuMy, en as menuEn } from "./menu";
import { my as customersMy, en as customersEn } from "./customers";
import { my as inventoryMy, en as inventoryEn } from "./inventory";
import { my as staffMy, en as staffEn } from "./staff";
import { my as reportsMy, en as reportsEn } from "./reports";
import { my as dashboardMy, en as dashboardEn } from "./dashboard";
import { my as settingsMy, en as settingsEn } from "./settings";
import { my as onlineMy, en as onlineEn } from "./online";

// Module dictionaries are registered here by the coordinator.
// Each module file exports `my` and `en` record objects.
// (Module agents: create src/lib/i18n/<module>.ts — do NOT edit this file.)

export type Lang = "my" | "en";

type ModuleDict = { my: Record<string, string>; en: Record<string, string> };

const modules: ModuleDict[] = [
  { my: commonMy, en: commonEn },
  { my: posMy, en: posEn },
  { my: ordersMy, en: ordersEn },
  { my: kdsMy, en: kdsEn },
  { my: tablesMy, en: tablesEn },
  { my: menuMy, en: menuEn },
  { my: customersMy, en: customersEn },
  { my: inventoryMy, en: inventoryEn },
  { my: staffMy, en: staffEn },
  { my: reportsMy, en: reportsEn },
  { my: dashboardMy, en: dashboardEn },
  { my: settingsMy, en: settingsEn },
  { my: onlineMy, en: onlineEn },
];

function merge(dicts: Record<string, string>[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (const d of dicts) Object.assign(out, d);
  return out;
}

export const dictionaries: Record<Lang, Record<string, string>> = {
  my: merge(modules.map((m) => m.my)),
  en: merge(modules.map((m) => m.en)),
};

export function serverT(lang: Lang, key: string, vars?: Record<string, string | number>): string {
  const dict = dictionaries[lang] ?? {};
  let s: string = dict[key] ?? dictionaries.en[key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v));
  }
  return s;
}
